### DISCUSSION TITLE
How do I add the "What's next?"

### DISCUSSION THREAD

**Discussion by thenerdassassin** [readmeio/rdme#853] [Q&A] [answered]
When using the API and SDK, how do I signify which page links for "What's next?"

**Comment by kanadgupta** [comment, marked as answer]
Hi there!

The attributes you're asking about are technically an undocumented part of [ReadMe's Docs API](https://docs.readme.com/main/reference/getdoc). As a disclaimer, these attributes are deliberately undocumented and might change without warning. For the upcoming version of the API (details to come), we should have better coverage on this front!

As of this writing, you can sync using [`rdme docs`](https://github.com/readmeio/rdme#docs-aka-guides-), you can [specify the following attributes in the YAML front matter](https://docs.readme.com/main/docs/rdme#/specifying-other-attributes) of your Markdown docs and an object like this will set the "What's Next" attributes:

```yml
next:
  pages:
    - name: Example Page
      slug: getting-started
      type: doc
      category: Documentation
    - type: url
      value: "https://google.com"
      name: some external link
```

Hope that helps! Feel free to [open up an issue](https://github.com/readmeio/rdme/issues/new) if you have any more questions 🙂

Thanks,

-Kanad
