### ISSUE TITLE
Add github action to docs

### ISSUE THREAD

**Issue by mikepage** [readmeio/rdme#1275]
API docs for ReadMe are not up to date ironically, this Github action works

```
name: Sync OpenAPI definition to ReadMe

# Run workflow for every push to the `main` branch
on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        # We recommend specifying a fixed version, i.e. @v10
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@v10
        with:
          rdme: openapi upload  ./var/openapi.json --slug=SLUG.json --key=${{ secrets.README_API_KEY }}
```

**Comment by mikepage** [comment]
Hi @kanadgupta.

Thanks for the quick reply. We had a self managed docker image for rdme cli with `npm install -g rdme@10`, we had a schedule to build a new version every day, however it pulled the npm dependencies from cache in Github actions.

Log output

```
#8 [2/4] RUN npm install -g rdme@10 && npm cache clean --force
#8 CACHED
```

Docker is fun until it isn't. Much better to use the github action provided by rdme. The docs I was referring to are here: https://docs.readme.com/main/docs/rdme#github-actions-usage

Adding a validate github action with one line is very nice.
```
rdme openapi validate --github
```

Then the documentation/guide is about Github secrets with validate in the example yaml:
https://docs.readme.com/main/docs/rdme#securely-using-your-api-key

```
- uses: readmeio/rdme@v10
  with:
    rdme: openapi validate [url-or-local-path-to-file] --key=${{ secrets.README_API_KEY }} --id=API_DEFINITION_ID

```

This example should be `openapi upload` not `openapi validate`, --id does not exists in `rdme@10 openapi upload`, --slug should be used.

```
- uses: readmeio/rdme@v10
  with:
    rdme: openap
          rdme: openapi upload  ./var/openapi.json --slug=SLUG.json --key=${{ secrets.README_API_KEY }}
```

A full example for lazy developers with the default Github action wrapper would be nice.
