### ISSUE TITLE
`undefined` error with pages created with 'createDoc' API w/ rdme@6.5.0

### ISSUE THREAD

**Issue by charyeezy** [readmeio/rdme#483]
I am currently trying to create one-way sync from Github to Readme so our repo is source of truth.

I am running into an error trying to sync pages after creating new page with [createDoc](https://docs.readme.com/reference/createdoc) API.

Returning an 'undefined' error

```
❯ npx rdme ...docs/ --version=1.4.5 --key xxx

Error uploading ...docs/clustering-features/clustering/subclustering.md

undefined
```

Frontmatter of the file as stated [here](https://docs.readme.com/docs/rdme)in the 'Syncing Docs via CLI / GitHub' docs.

```yaml
---
title: "Subclustering"
slug: "subclustering"
excerpt: "Subclusetring example"
hidden: false
category: 623a96a3032c43002ef2c617
parentDoc: 623a96a3032c43002ef2c68d
---
```

Please let me know if I am doing sth wrong here! 
```
❯ npx rdme --version
6.5.0
```
