### ISSUE TITLE
Unable to use output of rdme GitHub Action in subsequent jobs & commands

### ISSUE THREAD

**Issue by taycaldwell** [readmeio/rdme#515]
```
name: GitHub Action Demo
on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: GitHub Action
        uses: readmeio/rdme@7.2.0
        with:
          rdme: versions --raw --key <API_KEY>
```

I want to use the output of a rdme command in subsequent steps, or pipe it to another command, however I am limited to only running a single rdme command within a step.

For example, if I want to get the latest version, I cannot do:
`rdme versions --key <API_KEY> --raw | jq .[-1].version`

is there a way to use rdme CLI within a `run` of a GitHub Action besides running single commands the `with` `rdme` syntax?

**Comment by kanadgupta** [comment]
Hey @taycaldwell! Not sure off the top of my head if `jq` is installed in GitHub Actions environments, so the first step will be to install that if it's not already present.

The `with:` `rdme:` syntax is just syntactical sugar for the shell command, so you should be able to do something like:
```yml
- name: GitHub Action
  uses: readmeio/rdme@7.2.0
  with:
    rdme: versions --raw --key=<API_KEY> | jq
```

but if that doesn't work, then you can just install and run `rdme` via `npx` using `run` statements, with something like this:
```yml
- name: Install and run rdme
  run: |
    npm install rdme
    npx rdme versions --raw --key=<API_KEY> | jq
    <any other statements you want to run>
```
Let us know if you have any troubles with this approach. Thanks!
