### ISSUE TITLE
Slug conflict when syncing forked docs

### ISSUE THREAD

**Issue by taycaldwell** [readmeio/rdme#519]
I have two Github Action workflows. Each one runs a Readme Doc Sync for specific versions.

**Sync v1 of docs**

```
name: GitHub Actions Demo
on: [push]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: GitHub Action
        uses: readmeio/rdme@7.1.0
        with:
          rdme: docs ./docs/v1 --key=<KEY> --version=1.0.0
```

**Sync v2 of docs**

```
name: GitHub Actions Demo
on: [push]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: GitHub Action
        uses: readmeio/rdme@7.1.0
        with:
          rdme: docs ./docs/v2 --key=<KEY> --version=2.0.0
```

I created v2 as a fork of v1 under `Manage versions` of the Readme UI.

The sync for v1 works fine, however the sync for v2 fails because of conflicting slugs:

```
Error uploading docs/v2/page.md: We couldn't save this doc (Page slug must be unique.).
```

Is this intended behavior? Unique slugs makes sense for a specific version, however, since new versions are forked from older versions, isn't it assumed that the slugs will be duplicated? It seems to be true when I query for slugs using the ReadMe API.
