### ISSUE TITLE
How to sync Readme.io file with Gitlab? Getting error: unknown option '--key=xxxxxx" error

### ISSUE THREAD

**Issue by aimanalmas97** [readmeio/rdme#573]
I am trying to sync my readme.io API doc with my Gitlab for automatic updates, however I am getting the following error after I run the CI/CD pipeline. 

` error: unknown option '--key=rdme_xxxxxxx....'`

This is inside my .gitlab-ci.yml file

   
```

    image: node:14
    sync-via-rdme:
      script:
        - npx -y rdme@7.5.0 openapi file.json --key=xxxxxx --id=xxxxxx
```

When I run it using this command locally via VScode terminal it works, but when I do it via GitLab CI changes are not pushed into the readme.io API Reference. I want to be able to do it via GitLab CI.

 `   npx -y rdme@7.5.0 openapi file.json --key=rdme_xxxxx  --id=xxxxx`

Copied the format from readme.io docs for Gitlab's integration (https://docs.readme.com/docs/rdme#example-syncing-an-openapi-definition), what am I doing wrong?

**Comment by kanadgupta** [comment]
Hi @aimanalmas97! Thanks for writing in, sorry you're seeing this error... I confirmed that that `npx` command works fine [in GitHub Actions](https://github.com/kanadgupta/metrotransit-nextrip-oas/actions/runs/2890244084/workflow#L15-L16) 🤔  

Could you add the following environmental variable to your GitLab CI and send across the output you see?

```sh
DEBUG=rdme*
```

Here are GitLab's docs on adding environmental variables to GitLab CI: https://docs.gitlab.com/ee/ci/variables/index.html

**Comment by kanadgupta** [comment]
Hi @aimanalmas97! After digging into this deeper, we figured out that this was an issue with `npx@6`. The command should work properly if you you drop the `-y` option from your command, so it looks like this:

```yml
    image: node:14
    sync-via-rdme:
      script:
        - npx rdme@7.5.0 openapi file.json --key=xxxxxx --id=xxxxxx
```

I've updated our docs in https://github.com/readmeio/rdme/commit/3c9f4bf64c997634cb09e96a94f3f6a77da3e69e to reflect this. Let me know if you have any more questions/issues with this.

Thanks for writing in about this!

-Kanad
