### ISSUE TITLE
new CLI openapi: reduce option to change the "title" and consequently the "category" in API Reference

### ISSUE THREAD

**Issue by janiksam** [readmeio/rdme#716]
Hello team,

Our openapi file size requires us to use the `openapi:reduce` method in order to successfully upload the OpenAPI using Github Actions.

I would like to request an option in the `openapi:reduce` method to change the `title` of the info object in the reduced file. The reason is that each time I sync using the `openapi:reduce` method, the category in readme API reference gets changed to the value defined in `title`.  

```
"info": {
    {
        "title": "Reduced File Title that becomes the Category Name in API Reference"
        "version": ...
    }
}
```
I tried changing the category name in readme's Dashboard, but the change is overwritten during the syncing process.

Suggestion: 
- `--title "Category Title"`
- `--category "Category Title"`

Something along the lines of

```
- name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --path /metadata-schemas --method get --title "Metadata Schemas API" --out OpenAPI-reduced-metadata-schemas-api.json
```

Please let me know if you need any additional information. We would greatly appreciate your help.

Thanks!
