### ISSUE TITLE
new CLI doc option: reorder docs by checking front matter of all docs in the repository regardless of whether there was/wasn't a change

### ISSUE THREAD

**Issue by janiksam** [readmeio/rdme#731]
Hello team,

Our flow is to update the OpenAPI spec through GitHub actions and then update the order of the endpoints using front matter found in corresponding markdown files in the repository. 

I would like to request a `force` option in the `docs` method for the engine to go through all the docs in the master branch and update the order of my endpoints by looking at the front matter of the markdown files. In other words, I would like the CLI to look at all the docs as opposed to only docs that have changed or were updated since the last sync to readme.

Something along the lines of (the option could be named differently of course other than `--force`, for example, `--re-order`, `--all`)

```
- name: Sync docs to ReadMe
        if: github.event_name == 'push' && github.event.ref == 'refs/heads/master'
        uses: readmeio/rdme@8.4.0
        with:
          rdme: docs ./docs --key=${{ secrets.README_API_KEY }} --version=${{ secrets.README_MAIN_VERSION }} --force
```

Please let me know if you need any additional information. We would greatly appreciate your help.

Thanks!
Sam
