### ISSUE TITLE
TS errors with readmeio/rdme@8.5.0 GH action

### ISSUE THREAD

**Issue by KatKmiotek** [readmeio/rdme#757]
Hi, 
I am about to update GH action version used within the project from 7.2.1 to 8.5.0.
Is it something I miss from env setup to run this action?
![image](https://user-images.githubusercontent.com/62500625/218711981-1e9db6db-16d7-48a9-b21c-e008a7fdebc7.png)

**Comment by kanadgupta** [comment]
Hi @KatKmiotek! It's possible that you may have hit a temporary blip in availability of the `npm` registry. What happens if you try re-running this workflow? And could you send across a copy of your GitHub Actions workflow file?

Thanks!

**Comment by KatKmiotek** [comment]
Hi, I have tried to run it yesterday and twice today, no luck with retries. The yaml for workflow hasn't changed at all just the version. Using CLI 
```
 - name: Update readme.io
    uses: readmeio/rdme@8.5.0
       with:
           rdme: openapi './swagger.json' --key=${{ secrets.README_API_KEY }} --id=${{ secrets.INTERNAL_API_DEFINITION_ID }}
```
tried readmeio/rdme@8.5.0 and readmeio/rdme@v8.5.0
